[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = ["-C", "target-feature=-crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "clang"
rustflags = ["-C", "target-feature=-crt-static"]