name: platform-build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-platform-artifacts:
    name: build-platform-artifacts
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Setup Rust

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install Rust Targets
        run: rustup target add x86_64-unknown-linux-gnu x86_64-unknown-linux-musl aarch64-unknown-linux-gnu aarch64-unknown-linux-musl

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install
      
      - name: Run Release Build
        run: pnpm build:release      

      - name: Show Dist Files
        run: |
          echo "Contents of ./dist:"
          ls -alh ./dist

      - name: Show Src Files
        run: |
          echo "Contents of ./src:"
          ls -alh ./src

      - name: Run Tests
        run: pnpm test:ci