name: tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-test:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Setup Rust
      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install
      
      - name: Run Build
        run: pnpm build

      - name: Run Tests
        run: pnpm test:ci